# Generated by Django 5.0.4 on 2024-04-18 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('Login', models.CharField(max_length=250)),
                ('Password', models.CharField(max_length=250)),
                ('ID_Roles', models.CharField(max_length=250)),
            ],
        ),
    ]
