# Generated by Django 5.0.4 on 2024-04-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name_Film', models.CharField(max_length=250)),
                ('Duration_of_the_film', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=500)),
                ('year_production', models.DateField()),
                ('Country', models.CharField(max_length=250)),
                ('Genre', models.CharField(max_length=250)),
                ('Director', models.CharField(max_length=250)),
                ('Budget', models.CharField(max_length=250)),
                ('Fees_in_the_world', models.CharField(max_length=250)),
                ('Age_restrictions', models.CharField(max_length=250)),
                ('World_premiere', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='ID_Roles',
            field=models.IntegerField(),
        ),
    ]
