# Generated by Django 5.0.4 on 2024-04-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0002_films_alter_users_id_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='films',
            name='World_premiere',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='films',
            name='year_production',
            field=models.CharField(max_length=250),
        ),
    ]
