# Generated by Django 5.0.4 on 2024-04-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0003_alter_films_world_premiere_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=1000)),
                ('Rate', models.IntegerField()),
                ('ID_User', models.IntegerField()),
                ('ID_Films', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=250)),
            ],
        ),
    ]
