# Generated by Django 5.0.4 on 2024-04-21 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0004_reviews_roles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
