# Generated by Django 5.0.4 on 2024-04-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0005_rename_films_film_rename_reviews_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
