# Generated by Django 5.0.4 on 2024-04-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0006_alter_review_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Photo',
            field=models.ImageField(default=2, upload_to='static/Image/'),
            preserve_default=False,
        ),
    ]
