# Generated by Django 5.0.4 on 2024-04-24 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0007_film_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Name_Film_Eng',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
    ]
