# Generated by Django 5.0.4 on 2024-04-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myop', '0008_film_name_film_eng'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='Video',
            field=models.FileField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
